### PR TITLE
resolve whitelist bug where whitelisted items were still marked as selected (although visually they looked deselected)

### PR DESCRIPTION
**Pull request by leopoldjoy**

### CODE REVIEW

**Comment by valerybugakov** [comment]
@leopoldjoy hey, thanks again for your PR! Don't you think that whiteListed items shouldn't appear in `selecting` set at all? I've updated master branch to fix that. Let me know what do you think about it :)

**Comment by leopoldjoy** [comment]
@valerybugakov Yeah, that looks like a better approach. Do you think you could push your changes to `NPM` so that I can use it in a project? Thank you! 👍

**Comment by valerybugakov** [comment]
@leopoldjoy yep, will publish new version now! Thanks for pointing to this issue 👍

**Comment by leopoldjoy** [comment]
@valerybugakov Thanks! It looks like the `dist` files were not recompiled, only the `lib` files in the `NPM` package. Is it possible that `prepublish` and `dist` were not run prior to pushing to `NPM`?

**Comment by valerybugakov** [comment]
@leopoldjoy uugh, you're right :) Can you check it now? Should be compiled properly.

**Comment by leopoldjoy** [comment]
@valerybugakov Great, thanks so much! 👍

**Pull request closed without merging**
